# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{aussie-bonds}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Robert Brown"]
  s.date = %q{2010-10-05}
  s.description = %q{Pricing fomulae for Australian bonds}
  s.email = %q{robert.brown@treasurytechnology.com.au}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "aussie-bonds.gemspec",
     "lib/aussie-bonds.rb",
     "lib/extensions.rb",
     "lib/financial/security/coupon_bearing_accrue_close.rb",
     "lib/financial/security/coupon_bearing_base.rb",
     "lib/financial/security/rba/capital_indexed.rb",
     "lib/financial/security/rba/fixed_interest.rb",
     "lib/financial/security/rba/floating_rate_note.rb",
     "lib/financial/security/rba/treasury_note.rb",
     "lib/util.rb",
     "test/helper.rb",
     "test/test_aussie-bonds.rb",
     "test/treasury_note_test.rb"
  ]
  s.homepage = %q{http://github.com/rob99/aussie-bonds}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Pricing fomulae for Australian bonds}
  s.test_files = [
    "test/treasury_note_test.rb",
     "test/test_aussie-bonds.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

